language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: '9.6'
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: NuFoVzljFKwB1C5IFSRw7Ycz1VL7JbCePQGlL/zahRlEL4KN+6I14HUX6+DEgy+kI6apf9Ry91A71h4W/dNUbvjLgeAVBLc45Rhay5OZmebBCaOOEBsacjbcn+uuDqWLk3fhUyUWbSadGk5/UkPge6q9iHkKQOvTHNQ/FSs81GOxfDqH4TCtFuUzbENVXuzd3SGgcKVYPL4b9SCYXyrNTMm000KzlBi+H0hV142bpL19FqoeaIwMYgwq8yyaYblv8HfRBcogsfSsMOI/yysc0dkPw9cPDugKUTIlW1DAIa7k3dxneOdl8zKxxB2whGB6CoKJjjzz07K17zpUeItEsl3l5pWt6vHCrSgUyKCCzi3IvxKpf+bd/Y12R5BGoa2sFbYZf2kX9ppaOUbPo9CCPmq0CpoofN5Y9hg9CkJvC86XBnZRfYTXZL3rSTbiiMmxYcnKCfOGYS18BdNdzR+Bo1pSOYgtjvG4WIC3f615aqA7pi/bSPGJeByGrudKveR1NE/HHXp8/NhC1P1JO3HF/dtb7+niGhp/Fp2g6FhSV5GXr+dqvO6p48iFjuzB9oHoQszvbrpfkVkpBuAU3srWSXRr6SqeUm/xi+zRqONDkW+OOwwkSabuZFpJlJ0T27UQ719q/3I2IF+tZP8vSLw2GzFUjk3PYZu+3CloTLCe46E=
  app: solar-garden-fe
  on:
    repo: My-Solar-Garden/front_end_rails
    branch: main
  skip_cleanup: 'true'
