language: ruby
rvm:
- 2.5.3
addons:
  postgresql: '9.6'
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: R9fuVTMvvm0c8Ctg4iNfGBT2hvTC6HxZG7SUL9D+xQIhGlGj2DPu5zhwJ7FYlVLcPFAsSqKPM7YRbhUmt0XiRKZcMH6DIj3XXaNFZD9PN1j87te7GrFEhQCdNNMDGqcEu+GfD5sJ2saCEndOL4+1jY7AwdKY5luL7wtnqxzAQP/DTSLAgHV2NhnpcUM8U/wFdzXehRKkX/B2lmivrNKaNStXXjOLsk9Dr8VE/S657JKis1l7ykxXN6zYHz+jP9b2FGDJXcmyVVVug4I1HfzbxSOfMemsneIlAy7mhSNsMnzttE3VMMdzA8er7m7QtAK4JvyUiOHsc4D7DHlR/jNxCKrFWptp+z8RZnPpNHzx7u77LSfdmVSH6kJY7LWZqXvJe9JCjY6AQaO6WukdDs3qWd/1yl3rtUBFngWXikrX02HKTCcc04N4xd6g7c/GC0n2SQP4OQvgxs/edmg+6DyaL9kotBoOBVRQFoKNt1+dPtvyR7cx7Ogr6+GplA4geStoZmC/Uw4kq9TNxzAFKQ2lxGuSESe1XEtZnInRyn/MUSkR1F6STpL6AwUG7Moc8jrQDco6ntXPX1mJFKDKaGjLX/8US2M3+/rVNyaFR0PNZbU+h4QSHjv6r+LxGtFA3TNtCVfxb02lCX07T44dQe/gFiWlplh9OyZ4ePMm+it2TI4=
  app: solar-garden-fe
  on:
    repo: My-Solar-Garden/front_end_rails
    branch: main
  cleanup: false
  run: rails db:migrate
