language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: '9.6'
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: YiLFdW2zyWAULECQotmLdqdEexbvtRQAm2p8fuVturlxh2dpD6r5fEWmeVjWb39uLcFA1N0kMqwccrK5DalbBfT0DGh8O0kQicokJSJ4MFBtKvLhTmcc5U8xH3yfGUpES4oATmf5oSSDlpj1ZCyDDsNqtZ7RPkcATC3e0ArjeF/VEIp8CX0/q8xwqa/zQYJwzN+F12W+VGVhdg5wHfUDWp5uQy6F3IvbseAuzLERWTWgh/uWmOJvuZ81bcLUnN30F9Rynn4BYD1XZSIIxUoWDN2IIvo69fqOQxPVW11n4jfPQAi3Jn742PphEhW0r2aak74ixostt7J51vKOT+sFmLs7FeOyHLu4n6j4oR/bpB8Q59njJiaaeqDnJ/RnGM/JHtW6EOVWBmQt6LLefeDlxxYHnnI7RdNdSlVK3Fqrf+owxyPkRmpJBV15y/zwT7n7eQmYURb1yQJqFQb0D7JlQju1iK88d5AXvpxKZ7czXu2pKZotwefhmIq9dRiJU+O8+itRAX6rPYAkJUgw7/Xhnp6pNgBI6g7rzr6Zo7WFhrdYXrdOphpdQvm338ucL971ytmIGkK0aKaJNwFzKB6y3z2l6P7jxxUPlB0/PEgGWwy0nJNoZrClO1kN0EnvQPKD7917EK4FZ25/pbOWekGOKsIJrIydUF+6i/EwdTjIXuE=
  app: solar-garden-fe
  on:
    repo: My-Solar-Garden/front_end_rails
    branch: main
  skip_cleanup: 'true'
