language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: '9.6'
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: ImsnkxEN3v94RmYDSa8eeNyUPR8W0f+N50I9Vv/meztsKtI12QT+EwK2YyvB23huzXdYZhZNgsxanN23f/SOFVsniB6oL7//sFuz/fqVsbiqly4g0RPHFV0tyhk7KTe192pm87J+KZ5wPRLOpeREjp46KtGUJG030Y4uamoZwWCNqSkN+KtnnbDnpF/IuR5DmbvIvNVWEhdK/TKmNGjWUx5bcTRqEFpCF0TUEdFJ1elmU59E81hndeCTzk+WP7ggcvWN6g5ce8qj/dDfG23wWk9bSUF7XyZ9MtHXSB/9fg6mkZWXodqSC1cUpjjP8tI+MlZOqPhm9RdJ4gBb82lAx2owFIbPnUEThG4J8FCKjgRPEqp9oGqhj6ki9yjV3jBAweFcKzHdAciNQ9q8H7b8Jd050m0vfNYUX835Q7B1YW8lnX82nEKXeeoI/Nqk6u4j4tSnh4f+LSLMHcUWcujBCzYZ+bKnHksIt4JL/ZfPVwD9y/AwQH6LHPfbTzWZ2ls4FGCJ8Rnaf1EYwr9LlDuAA65FxTBnYldOY4WbeU9jm74lkxf/uqS6peaIe6G7XwZ01tSjnYpVYar/nxEfLpAFhaIOR9f3Nj6emXsLqnIqxvZxrQF3HJrCpWcGbJz1PV6uCH2+O7z1B+CC+CoTQ5ASvErEnlraOIbRVzVqTyu8Vxs=
  app: solar-garden-fe
  on:
    repo: My-Solar-Garden/front_end_rails
    branch: main
  skip_cleanup: true